# Generated by Django 3.2.5 on 2021-08-13 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-date_posted',), 'verbose_name_plural': 'Reviews'},
        ),
    ]
